### ISSUE TITLE
1.2.12 seems broken?

### ISSUE THREAD

**Issue by andreas-h** [conda-forge/pyshp-feedstock#7]
On my system (Python2.7, Linux64), a `conda install -c conda-forge pyshp` leads to `import shapefile` raising an `ImportError`.  Also, I cannot find any `shapefile.py` file which is present in the platform-dependent 1.2.11 packages for my system.

**Comment by ocefpaf** [comment]
I just tested it and seems fine:

```shell
conda create --yes --name TEST python=2.7 pyshp --channel conda-forge
source activate TEST
ls $CONDA_PREFIX/lib/python2.7/site-packages/shapefile.py*

/home/filipe/miniconda3/envs/TEST/lib/python2.7/site-packages/shapefile.py
/home/filipe/miniconda3/envs/TEST/lib/python2.7/site-packages/shapefile.pyc

python -c "import shapefile; print(shapefile.__version__, shapefile.__file__)"

('1.2.12', '/home/filipe/miniconda3/envs/TEST/lib/python2.7/site-packages/shapefile.pyc')
```

**Comment by andreas-h** [comment]
Interesting.  Here, it doesn't:

    conda create --yes --name TEST python=2.7 pyshp --channel conda-forge
    source activate TEST
    ls $CONDA_PREFIX/lib/python2.7/site-packages/shapefile.py*                                                     

    zsh: no matches found: 
    /home2/hilboll/.local/easybuild/software/Anaconda3/4.2.0/envs/TEST/lib/python2.7/site-packages/shapefile.py*

**Comment by ocefpaf** [comment]
Can you send the the results of `conda list` and `conda info` for that env?

**Comment by andreas-h** [comment]
Sure :-)

Here's `conda list`:

    $ conda list                                                                                                            1 ↵
    # packages in environment at /home2/hilboll/.local/easybuild/software/Anaconda3/4.2.0/envs/TEST:
    #
    backports.shutil_get_terminal_size 1.0.0                      py_2    conda-forge
    ca-certificates           2017.7.27.1                   0    conda-forge
    certifi                   2017.7.27.1              py27_0    conda-forge
    decorator                 4.1.2                    py27_0    conda-forge
    enum34                    1.1.6                    py27_1    conda-forge
    ipython                   5.5.0                    py27_0    conda-forge
    ipython_genutils          0.2.0                    py27_0    conda-forge
    ncurses                   5.9                          10    conda-forge
    openssl                   1.0.2l                        0    conda-forge
    pathlib2                  2.3.0                    py27_0    conda-forge
    pexpect                   4.2.1                    py27_0    conda-forge
    pickleshare               0.7.4                    py27_0    conda-forge
    pip                       9.0.1                    py27_0    conda-forge
    prompt_toolkit            1.0.15                   py27_0    conda-forge
    ptyprocess                0.5.2                    py27_0    conda-forge
    pygments                  2.2.0                    py27_0    conda-forge
    pyshp                     1.2.12                     py_0    conda-forge
    python                    2.7.13                        1    conda-forge
    readline                  6.2                           0    conda-forge
    scandir                   1.5                      py27_1    conda-forge
    setuptools                36.3.0                   py27_0    conda-forge
    simplegeneric             0.8.1                    py27_0    conda-forge
    six                       1.11.0                     py_0    conda-forge
    sqlite                    3.13.0                        1    conda-forge
    tk                        8.5.19                        2    conda-forge
    traitlets                 4.3.2                    py27_0    conda-forge
    wcwidth                   0.1.7                    py27_0    conda-forge
    wheel                     0.29.0                   py27_0    conda-forge
    zlib                      1.2.11                        0    conda-forge

and here's `conda info`:

    $ conda info        
    Current conda install:
    
                   platform : linux-64
              conda version : 4.2.9
           conda is private : False
          conda-env version : 4.2.9
        conda-build version : 2.0.2
             python version : 3.5.2.final.0
           requests version : 2.11.1
           root environment : /home2/hilboll/.local/easybuild/software/Anaconda3/4.2.0  (writable)
        default environment : /home2/hilboll/.local/easybuild/software/Anaconda3/4.2.0/envs/TEST
           envs directories : /home2/hilboll/.local/easybuild/software/Anaconda3/4.2.0/envs
              package cache : /home2/hilboll/.local/easybuild/software/Anaconda3/4.2.0/pkgs
               channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                              https://repo.continuum.io/pkgs/free/noarch/
                              https://repo.continuum.io/pkgs/pro/linux-64/
                              https://repo.continuum.io/pkgs/pro/noarch/
                              https://conda.anaconda.org/conda-forge/linux-64/
                              https://conda.anaconda.org/conda-forge/noarch/
                config file : /home2/hilboll/.condarc
               offline mode : False

**Comment by ocefpaf** [comment]
Try to upgrade to `conda >=4.3`. That is the only difference I can see from your env and mine that could make a difference.

**Comment by andreas-h** [comment]
That indeed does the trick!  After updating conda in the default
environment, installation of pyshp-1.2.12 does give me the shapefile.py*
files.

Since I have no idea about all this noarch stuff, I'll leave it to you
to follow up on this issue.  Thanks for your help!

**Comment by ocefpaf** [comment]
I guess we need to update the docs and mention that we need an updated `conda` for `noarch`.
With that said `conda` is a fast evolving software, so keeping it updated is always good practice.
